# -*- coding: utf-8 -*-
"""Deep_NN_RPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEldbBNkXesYuwCZj_0SJPxeMmN_9ZXO
"""

from google.colab import drive
drive.mount('/content/drive')

# 1. Import Libraries

import tensorflow as tf
import os
import pathlib
import math
import random
import matplotlib.pyplot as plt
import numpy as np

# 2. Constants

IMG_HEIGHT = 224
IMG_WIDTH = 224
IMG_CHANNELS = 3

CLASS_NAMES = ["paper", "rock", "scissors"]

# 3. Read and Decode Image

def read_and_decode(filename, resize_dims):

    img_bytes = tf.io.read_file(filename)

    img = tf.image.decode_image(
        img_bytes,
        channels=IMG_CHANNELS,
        expand_animations=False
    )

    img = tf.image.convert_image_dtype(
        img,
        tf.float32
    )

    img = tf.image.resize(
        img,
        resize_dims
    )

    return img

# 4. CSV Parser

def parse_csvline(csv_line):

    record_default = ["",""]

    filename,label_string = tf.io.decode_csv(
        csv_line,
        record_default
    )

    img = read_and_decode(
        filename,
        [IMG_HEIGHT,IMG_WIDTH]
    )

    label = tf.argmax(
        tf.math.equal(
            CLASS_NAMES,
            label_string
        )
    )

    return img,label

# 5. Dataset Path

data_dir = pathlib.Path(
    "/content/drive/MyDrive/R_P_S_dataset"
)

print("Folders:")
print(os.listdir(data_dir))

# 6. Create Train and Eval CSV

random.seed(42)

TRAIN_CSV="/tmp/train_set.csv"
EVAL_CSV="/tmp/eval_set.csv"

train_rows=[]
eval_rows=[]

for cls in CLASS_NAMES:

    cls_dir = data_dir / cls

    images=[]

    images += list(cls_dir.glob("*.jpg"))
    images += list(cls_dir.glob("*.jpeg"))
    images += list(cls_dir.glob("*.png"))

    images=[
        str(img)
        for img in images
    ]

    print(
        cls,
        "images found:",
        len(images)
    )

    random.shuffle(images)

    split = math.ceil(
        len(images)*0.8
    )

    train_rows += [
        (p,cls)
        for p in images[:split]
    ]

    eval_rows += [
        (p,cls)
        for p in images[split:]
    ]

random.shuffle(train_rows)
random.shuffle(eval_rows)

with open(TRAIN_CSV,"w") as f:

    for path,label in train_rows:

        f.write(
            f"{path},{label}\n"
        )

with open(EVAL_CSV,"w") as f:

    for path,label in eval_rows:

        f.write(
            f"{path},{label}\n"
        )

print("----------------")
print("Train samples :",len(train_rows))
print("Eval samples :",len(eval_rows))

# 7. Create TensorFlow Dataset

train_dataset=(

    tf.data.TextLineDataset(TRAIN_CSV)

    .map(
        parse_csvline,
        num_parallel_calls=tf.data.AUTOTUNE
    )

    .batch(16)

    .prefetch(tf.data.AUTOTUNE)
)

eval_dataset=(

    tf.data.TextLineDataset(EVAL_CSV)

    .map(
        parse_csvline,
        num_parallel_calls=tf.data.AUTOTUNE
    )

    .batch(16)

    .prefetch(tf.data.AUTOTUNE)
)

print("Datasets ready")

# 8. Display One Image

for image_batch,label_batch in train_dataset.take(1):

    plt.imshow(
        image_batch[0].numpy()
    )

    plt.title(
        CLASS_NAMES[label_batch[0]]
    )

    plt.axis("off")
    plt.show()

# 9. Display 16 Images

for image_batch,label_batch in train_dataset.take(1):

    fig,axes=plt.subplots(
        4,
        4,
        figsize=(10,10)
    )

    for i in range(16):

        ax=axes[
            i//4,
            i%4
        ]

        ax.imshow(
            image_batch[i].numpy()
        )

        ax.set_title(
            CLASS_NAMES[label_batch[i]]
        )

        ax.axis("off")

    plt.tight_layout()
    plt.show()

# 10. Neural Network with 2 hidden layers

model=tf.keras.Sequential([

    tf.keras.layers.Flatten(
        input_shape=(224,224,3)
    ),

    tf.keras.layers.Dense(
        128,
        activation="relu"
    ),

    tf.keras.layers.Dense(
        64,
        activation="relu"
    ),

    tf.keras.layers.Dense(
        3,
        activation="softmax"
    )
])

# 11. Compile

model.compile(

    optimizer="adam",

    loss="sparse_categorical_crossentropy",

    metrics=["accuracy"]
)

# 12. Train

EPOCHS=5

history=model.fit(
    train_dataset,
    validation_data=eval_dataset,
    epochs=EPOCHS
)

# 13. Loss and Accuracy Graph

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# 14. Prediction Visualization

for images,labels in eval_dataset.take(1):

    predictions=model.predict(images)

    predicted_indices=np.argmax(
        predictions,
        axis=1
    )

    num_images=images.shape[0]

    cols=4

    rows=math.ceil(
        num_images/cols
    )

    plt.figure(
        figsize=(12,3*rows)
    )

    for i in range(num_images):

        plt.subplot(
            rows,
            cols,
            i+1
        )

        plt.imshow(
            images[i].numpy()
        )

        plt.axis("off")

        pred_class=CLASS_NAMES[
            predicted_indices[i]
        ]

        actual_class=CLASS_NAMES[
            labels[i].numpy()
        ]

        plt.title(
            f"Pred: {pred_class}\nActual: {actual_class}"
        )

    plt.tight_layout()
    plt.show()

# 15. Final Accuracy

loss,accuracy=model.evaluate(
    eval_dataset
)

print(
    "Test Accuracy:",
    accuracy
)





